<?php

return [
    // Report Types
    'reports_title' => 'Reports',
    'reports_exam' => 'Exam Reports',
    'reports_fee' => 'Fee Reports',
    'reports_attendance' => 'Attendance Reports',
    'reports_student' => 'Student Reports',
    'reports_staff' => 'Staff Reports',
    'reports_library' => 'Library Reports',
    'reports_inventory' => 'Inventory Reports',
    'reports_expense' => 'Expense Reports',
    
    // Printable Report Names
    'report_exam_transcript' => 'Exam Transcript',
    'report_exam_average_result' => 'Exam Average Result',
    'report_exam_award_list' => 'Exam Award List',
    'report_exam_tabulation' => 'Exam Tabulation Sheet',
    'report_fee_collection' => 'Fee Collection Report',
    'report_fee_receipt' => 'Fee Receipt Statement',
    'report_daily_collection' => 'Daily Fee Collection',
    'report_unpaid_fees' => 'Unpaid Fee Statement',
    'report_yearly_collection' => 'Yearly Collection Statement',
    'report_freeship_list' => 'Free Scholarship Students List',
    'report_attendance_sheet' => 'Attendance Sheet',
    'report_seats_status' => 'Seats Status Report',
    'report_student_transfer_cert' => 'Student Transfer Certificate',
    'report_student_idcard' => 'Student ID Card',
    'report_system_invoice' => 'System Invoice History',
    'report_sms_history' => 'SMS History',
    
    // Report Sections
    'report_summary' => 'Summary',
    'report_details' => 'Details',
    'report_footer' => 'Footer',
    'report_header' => 'Header',
    'report_generated_on' => 'Generated On',
    'report_generated_by' => 'Generated By',
    'report_page' => 'Page',
    'report_of' => 'of',
    'report_confidential' => 'Confidential',
    'report_draft' => 'Draft Copy',
    'report_official' => 'Official Copy',
    
    // Export Formats
    'export_pdf' => 'Export as PDF',
    'export_excel' => 'Export as Excel',
    'export_csv' => 'Export as CSV',
    'export_print' => 'Print Report',
    
    // Report Filters
    'filter_date_range' => 'Date Range',
    'filter_class' => 'By Class',
    'filter_section' => 'By Section',
    'filter_student' => 'By Student',
    'filter_session' => 'By Session',
    'filter_exam' => 'By Exam',
    'filter_month' => 'By Month',
    'filter_status' => 'By Status',
    
    // Chart & Graph
    'chart_title' => 'Chart',
    'chart_student_performance' => 'Student Performance Chart',
    'chart_fee_collection' => 'Fee Collection Chart',
    'chart_attendance_trend' => 'Attendance Trend',
    'chart_monthly_stats' => 'Monthly Statistics',
    'chart_class_wise' => 'Class Wise Distribution',
    'chart_section_wise' => 'Section Wise Distribution',
];
